import{a as $,i as u,S as C}from"./assets/vendor-ee72e1a4.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const n={page:1,perPage:15},h=document.querySelector(".loader");function E(){h.style.display="flex"}function m(){h.style.display="none"}async function g(e){const o=new URLSearchParams({key:"44773491-691b01ebde89d181347bf66a7",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:n.perPage,page:n.page});return E(),await $.get(`https://pixabay.com/api/?${o}`).then(i=>i.data)}function y(e){u.error({title:"Error",message:"2Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}const f=document.querySelector(".card-container");async function b(e){const o=e.map(({webformatURL:l,largeImageURL:t,tags:r,likes:s,views:q,comments:x,downloads:v})=>`<li class="gallery-item">
            <a class="gallery-link" href="${t}">
                <img class="gallery-image" src="${l}" alt="${r}" width="360" height="200"/>
                <ul class="gallery-text-list">
                    <li class="gallery-text-item"><h3>Likes</h3><p>${s}</p></li>
                    <li class="gallery-text-item"><h3>Views</h3><p>${q}</p></li>
                    <li class="gallery-text-item"><h3>Comments</h3><p>${x}</p></li>
                    <li class="gallery-text-item"><h3>Downloads</h3><p>${v}</p></li>
                </ul>
            </a>
        </li>`).join("");f.insertAdjacentHTML("beforeend",o),new C(".card-container a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const M=document.querySelector(".search-form"),a=document.querySelector(".btn-load-more");document.querySelector(".loader");const L="is-hidden";let c="",d=0;M.addEventListener("submit",R);function p(e){e.classList.add(L)}function O(e){e.classList.remove(L)}function w(e){e.disabled=!0}function S(e){e.disabled=!1}p(a);async function R(e){e.preventDefault(),f.innerHTML="";const o=e.currentTarget;if(c=o.elements.query.value.trim(),c===""){w(a),u.warning({title:"Caution",message:"Please, enter in the photo",position:"topRight"}),o.reset();return}try{let i=await g(c);if(b(i.hits),O(a),d=Math.ceil(i.total/n.perPage),n.page>d)return p(a),u.error({position:"topRight",message:"We're sorry, there are no more posts to load"});S(a),a.addEventListener("click",P)}catch{y()}finally{m(),o.reset()}}async function P(){w(a),n.page+=1;try{let e=await g(c);b(e.hits);const i=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}catch(e){console.error(e),y()}finally{S(a),n.page>=d&&(p(a),a.removeEventListener("click",P),u.warning({title:"Caution",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),m()}}
//# sourceMappingURL=commonHelpers.js.map
