import{a as $,i as c,S as C}from"./assets/vendor-ee72e1a4.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const n={page:1,perPage:15},p=document.querySelector(".loader");function E(){p.style.display="flex"}function g(){p.style.display="none"}async function h(e){const o=new URLSearchParams({key:"44773491-691b01ebde89d181347bf66a7",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:n.perPage,page:n.page});return E(),await $.get(`https://pixabay.com/api/?${o}`).then(a=>a.data)}function m(e){c.error({title:"Error",message:"2Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}const f=document.querySelector(".card-container");async function y(e){const o=e.map(({webformatURL:l,largeImageURL:t,tags:r,likes:s,views:q,comments:x,downloads:v})=>`<li class="gallery-item">
            <a class="gallery-link" href="${t}">
                <img class="gallery-image" src="${l}" alt="${r}" width="360" height="200"/>
                <ul class="gallery-text-list">
                    <li class="gallery-text-item"><h3>Likes</h3><p>${s}</p></li>
                    <li class="gallery-text-item"><h3>Views</h3><p>${q}</p></li>
                    <li class="gallery-text-item"><h3>Comments</h3><p>${x}</p></li>
                    <li class="gallery-text-item"><h3>Downloads</h3><p>${v}</p></li>
                </ul>
            </a>
        </li>`).join("");f.insertAdjacentHTML("beforeend",o),new C(".card-container a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const M=document.querySelector(".search-form");document.querySelector(".btn");const i=document.querySelector(".btn-load-more"),b="is-hidden";let u="",d=0;M.addEventListener("submit",R);function L(e){e.classList.add(b)}function O(e){e.classList.remove(b)}function P(e){e.disabled=!0}function S(e){e.disabled=!1}L(i);async function R(e){e.preventDefault(),f.innerHTML="";const o=e.currentTarget;if(u=o.elements.query.value.trim(),u===""){c.warning({title:"Caution",message:"Please, enter in the photo",position:"topRight"}),o.reset();return}O(i),P(i);try{let a=await h(u);if(y(a.hits),d=Math.ceil(a.total/n.perPage),console.log("totalPages:",d),console.log("pagination.page",n.page),n.page>d)return c.error({position:"topRight",message:"1We're sorry, there are no more posts to load"});a.total===0&&c.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),S(i),i.addEventListener("click",w)}catch(a){console.error(a),m()}finally{g(),o.reset()}}async function w(){P(i),n.page+=1;try{let e=await h(u);y(e.hits)}catch(e){console.error(e),m()}finally{S(i),g(),n.page===d&&(L(i),i.removeEventListener("click",w))}}
//# sourceMappingURL=commonHelpers.js.map
