import{a as $,i as u,S as C}from"./assets/vendor-ee72e1a4.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const n={page:1,perPage:15},y=document.querySelector(".loader");function E(){y.style.display="flex"}function h(){y.style.display="none"}async function f(e){const o=new URLSearchParams({key:"44773491-691b01ebde89d181347bf66a7",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:n.perPage,page:n.page});E();try{return(await $.get(`https://pixabay.com/api/?${o}`)).data}catch(a){throw g(),a}finally{h()}}function g(e){u.error({title:"Error",message:"2Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}const b=document.querySelector(".card-container");let d;async function I(){d?d.refresh():d=new C(".card-container a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250})}async function w(e){const o=e.map(({webformatURL:a,largeImageURL:l,tags:t,likes:r,views:s,comments:x,downloads:v})=>`<li class="gallery-item">
            <a class="gallery-link" href="${l}">
                <img class="gallery-image" src="${a}" alt="${t}" width="360" height="200"/>
                <ul class="gallery-text-list">
                    <li class="gallery-text-item"><h3>Likes</h3><p>${r}</p></li>
                    <li class="gallery-text-item"><h3>Views</h3><p>${s}</p></li>
                    <li class="gallery-text-item"><h3>Comments</h3><p>${x}</p></li>
                    <li class="gallery-text-item"><h3>Downloads</h3><p>${v}</p></li>
                </ul>
            </a>
        </li>`).join("");b.insertAdjacentHTML("beforeend",o),await I()}const M=document.querySelector(".search-form"),i=document.querySelector(".btn-load-more");document.querySelector(".loader");const L="is-hidden";let c="",p=0;M.addEventListener("submit",R);function m(e){e.classList.add(L)}function O(e){e.classList.remove(L)}function S(e){e.disabled=!0}function P(e){e.disabled=!1}m(i);async function R(e){e.preventDefault(),b.innerHTML="",n.page=1;const o=e.currentTarget;if(c=o.elements.query.value.trim(),c===""){S(i),u.warning({title:"Caution",message:"Please, enter in the photo",position:"topRight"}),o.reset();return}try{let a=await f(c);if(w(a.hits),O(i),p=Math.ceil(a.total/n.perPage),n.page>p)return m(i),u.error({position:"topRight",message:"We're sorry, there are no more posts to load"});P(i),i.addEventListener("click",q)}catch{g()}finally{h(),o.reset()}}async function q(){S(i),n.page+=1;try{let e=await f(c);w(e.hits);const a=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}catch(e){console.error(e),g()}finally{P(i),n.page>=p&&(m(i),i.removeEventListener("click",q),u.warning({title:"Caution",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),h()}}
//# sourceMappingURL=commonHelpers.js.map
